/**
 * License verification public key.
 *
 * GENERATED by tools/make-keypair.mjs. Safe to ship: it can only verify
 * signatures, never create them. The matching private key lives outside this
 * repository in .keys/private.jwk.json and must never be committed.
 */

export const LICENSE_PUBLIC_KEY = Object.freeze({
  "kty": "EC",
  "crv": "P-256",
  "x": "izoS1YjDuNIGDhJrsbSew0sdTeS6URmF-MUudbx1Ink",
  "y": "jNZmMsmq5-RFxD3TSggijR2LhWtqAKeEhHBp_tMrXdI"
});
