/**
 * Generates the licensing key pair.
 *
 *   - The PUBLIC key is written to shared/license-key.js and ships inside every
 *     extension, which is how a pasted license is verified offline.
 *   - The PRIVATE key is written to .keys/private.jwk.json, which is gitignored.
 *     It signs licenses at sale time and must never be committed or shipped.
 *
 * Run this ONCE. Regenerating it invalidates every license already sold.
 *
 * Usage: node tools/make-keypair.mjs [--force]
 */

import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PRIVATE_PATH = join(ROOT, '.keys', 'private.jwk.json');
const PUBLIC_PATH = join(ROOT, 'shared', 'license-key.js');

if (existsSync(PRIVATE_PATH) && !process.argv.includes('--force')) {
  console.error('A private key already exists at .keys/private.jwk.json');
  console.error('Regenerating it would invalidate every license already sold.');
  console.error('Pass --force only if you are certain.');
  process.exit(1);
}

const pair = await crypto.subtle.generateKey(
  { name: 'ECDSA', namedCurve: 'P-256' },
  true,
  ['sign', 'verify']
);

const privateJwk = await crypto.subtle.exportKey('jwk', pair.privateKey);
const publicJwk = await crypto.subtle.exportKey('jwk', pair.publicKey);

// Only the fields verification needs; `key_ops` and `ext` would just be noise.
const publishable = {
  kty: publicJwk.kty,
  crv: publicJwk.crv,
  x: publicJwk.x,
  y: publicJwk.y,
};

mkdirSync(dirname(PRIVATE_PATH), { recursive: true });
writeFileSync(PRIVATE_PATH, JSON.stringify(privateJwk, null, 2) + '\n');

writeFileSync(
  PUBLIC_PATH,
  `/**
 * License verification public key.
 *
 * GENERATED by tools/make-keypair.mjs. Safe to ship: it can only verify
 * signatures, never create them. The matching private key lives outside this
 * repository in .keys/private.jwk.json and must never be committed.
 */

export const LICENSE_PUBLIC_KEY = Object.freeze(${JSON.stringify(publishable, null, 2)});
`
);

console.log('Private key  ->  .keys/private.jwk.json   (gitignored, never ship this)');
console.log('Public key   ->  shared/license-key.js    (ships in every extension)');
console.log('\nRun `npm run sync` to copy the public key into each extension.');
